spring:
  application:
    name: eureka-service
  cloud:
    config:
      fail-fast: false
      retry:
        max-attempts: 6
        max-interval: 2000
        initial-interval: 1000
      enabled: true
      uri: http://localhost:8888
