server:
  port: 8085

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl: # Corregido a CamelCase como espera Spring
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    hostname: localhost
    prefer-ip-address: false

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: inventario-route
          uri: lb://m1-inventario
          predicates:
            - Path=/m1-inventario/**

        - id: prestamos-route
          uri: lb://m2-prestamos
          predicates:
            - Path=/m2-prestamos/**

        - id: clientes-route
          uri: lb://m3-clientes
          predicates:
            - Path=/m3-clientes/**

        - id: tarifas-route
          uri: lb://m4-tarifas
          predicates:
            - Path=/m4-tarifas/**

        - id: kardex-route
          uri: lb://m5-kardex
          predicates:
            - Path=/m5-kardex/**

        - id: reportes-route
          uri: lb://m6-reportes
          predicates:
            - Path=/m6-reportes/**

        - id: usuarios-route
          uri: lb://m7-usuarios
          predicates:
            - Path=/m7-usuarios/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
